### ISSUE TITLE
please extend debugpkgs-pull for c10s binaries

### ISSUE THREAD

**Issue by fche** [CentOS/ansible-role-debuginfod#2]
c10s binaries are starting to get served over on `odcs.stream.centos.org/stream-10/development/`, and people are starting to debug them.  So debuginfod.centos.org should start serving that content ASAP.

This will likely also need more storage over on the `debuginfod1.aws.centos.org` VM (unless we can figure out a way of letting the VM NFS-mount read-only, to fetch the files from an existing mirror).

```
Filesystem                                   1K-blocks        Used  Available Use% Mounted on
/dev/mapper/vg_debugstore-debuginfod_store 12150690604 10298511284 1851519448  85% /srv/debuginfod_store

```

**Comment by arrfab** [comment]
nothing is released and per discussion with the Stream team *nothing* should be used anywhere, as not signed and not announced (yet) .. I'll create a ticket on infra tracker as a reminder but we'll only be able to pull from released content once it will be released :) 

This will be so tracked in https://pagure.io/centos-infra/issue/1407
